/**
 * 料件管理系統 - 預置展示數據與無限制層級分類樹
 * 大項「零件」子項目：
 *   11X(電阻)、12X(電感)、13X(電容)、14(震盪器)、15(二極體)、
 *   16X(接頭)、17X(開關)、18X(線)、2XX(主動元件)、3XX(IC)、4XX(模組)
 * 大項「產品」子項目：
 *   RTK、BD
 *
 * 料件欄位完全對齊 Excel 圖片：
 * Group, type, Item, Class, Value/Name, Tolerance/Type, PCB footprint,
 * Manufacturer, M P/N, Vendor, Sample, Stock, MOQ, Unit price (TWD), Unit price (USD), 替代, Date
 */

// 1. 預設無限制層級分類樹結構
const INITIAL_CATEGORY_TREE = [
  {
    id: 'cat-parts',
    name: '零件',
    code: 'PARTS',
    parentId: null,
    isOpen: true,
    children: [
      { id: 'cat-11x', name: '11X(電阻)', code: '11X', parentId: 'cat-parts', isOpen: true, children: [] },
      { id: 'cat-12x', name: '12X(電感)', code: '12X', parentId: 'cat-parts', isOpen: true, children: [] },
      { id: 'cat-13x', name: '13X(電容)', code: '13X', parentId: 'cat-parts', isOpen: true, children: [] },
      { id: 'cat-14',  name: '14(震盪器)', code: '14',  parentId: 'cat-parts', isOpen: true, children: [
        { id: 'cat-14-1', name: '無源晶振 (Crystals)', code: '14-1', parentId: 'cat-14', isOpen: true, children: [] },
        { id: 'cat-14-2', name: '有源溫補晶振 (TCXO)', code: '14-2', parentId: 'cat-14', isOpen: true, children: [] }
      ]},
      { id: 'cat-15',  name: '15(二極體)', code: '15',  parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-16x', name: '16X(接頭)', code: '16X', parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-17x', name: '17X(開關)', code: '17X', parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-18x', name: '18X(線)',   code: '18X', parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-2xx', name: '2XX(主動元件)', code: '2XX', parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-3xx', name: '3XX(IC)',   code: '3XX', parentId: 'cat-parts', isOpen: false, children: [] },
      { id: 'cat-4xx', name: '4XX(模組)', code: '4XX', parentId: 'cat-parts', isOpen: false, children: [] }
    ]
  },
  {
    id: 'cat-products',
    name: '產品',
    code: 'PRODUCTS',
    parentId: null,
    isOpen: true,
    children: [
      { id: 'cat-rtk', name: 'RTK', code: 'RTK', parentId: 'cat-products', isOpen: true, children: [
        { id: 'cat-rtk-base', name: '基準站設備', code: 'RTK-BASE', parentId: 'cat-rtk', isOpen: true, children: [] },
        { id: 'cat-rtk-rover', name: '手持移動站', code: 'RTK-ROVER', parentId: 'cat-rtk', isOpen: true, children: [] }
      ]},
      { id: 'cat-bd', name: 'BD', code: 'BD', parentId: 'cat-products', isOpen: true, children: [] }
    ]
  }
];

// 2. 依據上傳之 Excel 圖片 Group 14 (震盪器 Crystals) 與經典電子物料轉錄之真實種子資料
const INITIAL_PARTS_SEED = [
  // --- Group 14 震盪器 Crystals (精確對齊使用者上傳之圖片每一列) ---
  {
    id: 'p-crys-1',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '90',
    class: 'Crystals',
    valueName: '32.768 kHz 7pF/20 PPM',
    toleranceType: '2x1.2x0.5',
    footprint: '2x1.2',
    manufacturer: '微基科技',
    mpn: 'CM8V-T1A32.768KHZ7.0PF±20PPMTAQC',
    vendor: '',
    sample: '',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-01',
    location: 'A棟-晶振架-01',
    safetyStock: 100
  },
  {
    id: 'p-crys-2',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '91',
    class: 'Crystals',
    valueName: '32.768 kHz 12.5pF/20',
    toleranceType: '3.2x1.5x0.9',
    footprint: 'ECX-34Q',
    manufacturer: 'ECS',
    mpn: 'ECS-.327-7-34B-TR',
    vendor: 'Mouser/251099483',
    sample: '1+100+10',
    stock: '',
    moq: '100',
    unitPriceTwd: '18.98',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-05',
    location: 'A棟-晶振架-02',
    safetyStock: 150
  },
  {
    id: 'p-crys-3',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '170',
    class: 'Crystals',
    valueName: '32.768 kHz 12.5pF/20',
    toleranceType: '3.2x1.5x0.9',
    footprint: 'ECX-34Q',
    manufacturer: 'ECS',
    mpn: 'ECS-.327-12.5-34QCS-TR',
    vendor: 'Arrow',
    sample: '12+10',
    stock: '',
    moq: '3000',
    unitPriceTwd: '33.92',
    unitPriceUsd: '0.34',
    substitute: '',
    date: '2026-03-08',
    location: 'A棟-晶振架-03',
    safetyStock: 200
  },
  {
    id: 'p-crys-4',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '170',
    class: 'Crystals',
    valueName: '32.768 kHz 12.5pF/20',
    toleranceType: '3.2x1.5x0.9',
    footprint: 'ECX-34Q',
    manufacturer: 'Epson',
    mpn: 'FC-135 32.768K-60AA70KDB',
    vendor: '',
    sample: '45',
    stock: '612',
    moq: '3000',
    unitPriceTwd: '2.8',
    unitPriceUsd: '0.34',
    substitute: '',
    date: '2026-03-10',
    location: 'A棟-晶振架-04',
    safetyStock: 500
  },
  {
    id: 'p-crys-5',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '170',
    class: 'Crystals',
    valueName: '32.768 kHz 12.5pF/20',
    toleranceType: '3.2x1.5x0.9 FC-135 2P',
    footprint: 'ECX-34Q',
    manufacturer: '',
    mpn: '',
    vendor: '',
    sample: '298',
    stock: '',
    moq: '',
    unitPriceTwd: '2.9',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-12',
    location: 'A棟-晶振架-05',
    safetyStock: 100
  },
  {
    id: 'p-crys-6',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '327',
    class: 'Crystals',
    valueName: '32.768 kHz 12.5pF/20',
    toleranceType: '6.9x1.4',
    footprint: '6.9x1.4',
    manufacturer: 'TXC',
    mpn: '9H03200413',
    vendor: '',
    sample: '202',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-15',
    location: 'A棟-晶振架-06',
    safetyStock: 150
  },
  {
    id: 'p-crys-7',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '327A',
    class: 'Crystals',
    valueName: '32.768kHz',
    toleranceType: '4.1x1.5x0.75mm',
    footprint: '4.1x1.5x0.75mm',
    manufacturer: 'TXC',
    mpn: '9H03200584',
    vendor: 'Arrow',
    sample: '32',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-16',
    location: 'A棟-晶振架-07',
    safetyStock: 50
  },
  {
    id: 'p-crys-8',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '172',
    class: 'Crystals',
    valueName: '6MHz',
    toleranceType: '',
    footprint: 'CSTCR6M00G53Z-R0',
    manufacturer: 'Murata',
    mpn: 'CSTCR6M00G53Z-R0',
    vendor: 'Avnet',
    sample: '16',
    stock: '3,000',
    moq: '3000',
    unitPriceTwd: '',
    unitPriceUsd: '0.122',
    substitute: '',
    date: '2026-03-20',
    location: 'A棟-晶振架-08',
    safetyStock: 1000
  },
  {
    id: 'p-crys-9',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '125A',
    class: 'Crystals',
    valueName: '12MHz 18F 20ppm',
    toleranceType: '4P',
    footprint: 'ECX-32(3.2x2.5x0.8)',
    manufacturer: 'ECS',
    mpn: 'ECS-120-18-33-JGN-TR',
    vendor: 'Mouser/251099483',
    sample: '10+100',
    stock: '',
    moq: '100',
    unitPriceTwd: '13.73',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-22',
    location: 'A棟-晶振架-09',
    safetyStock: 100
  },
  {
    id: 'p-crys-10',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '126',
    class: 'Crystals',
    valueName: '12MHz 18F',
    toleranceType: '4P_w/_Power',
    footprint: '3.2x2.5x1',
    manufacturer: 'Diodes',
    mpn: 'FK series',
    vendor: '',
    sample: '58',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-25',
    location: 'A棟-晶振架-10',
    safetyStock: 50
  },
  {
    id: 'p-crys-11',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '136',
    class: 'Crystals',
    valueName: '13MHz 15pF 25ppm 1.8V',
    toleranceType: '',
    footprint: 'ECX-32',
    manufacturer: 'TXC',
    mpn: '7X13000001',
    vendor: '',
    sample: '20',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-26',
    location: 'A棟-晶振架-11',
    safetyStock: 50
  },
  {
    id: 'p-crys-12',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '136A',
    class: 'Crystals',
    valueName: '13MHz 10pF 10ppm',
    toleranceType: '',
    footprint: 'ECX-32',
    manufacturer: 'TXC',
    mpn: '7M13000140',
    vendor: '',
    sample: '5+170',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-27',
    location: 'A棟-晶振架-12',
    safetyStock: 100
  },
  {
    id: 'p-crys-13',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '171',
    class: 'Crystals',
    valueName: '25MHz 20pF 30ppm',
    toleranceType: '6.0x3.5x1.1',
    footprint: 'ECS-250-18-23A-JGN-TR',
    manufacturer: 'ECS',
    mpn: 'ECS-250-18-23A-JGN-TR',
    vendor: 'Arrow',
    sample: '10+13+2+3',
    stock: '',
    moq: '1000',
    unitPriceTwd: '',
    unitPriceUsd: '0.438',
    substitute: '',
    date: '2026-03-28',
    location: 'A棟-晶振架-13',
    safetyStock: 200
  },
  {
    id: 'p-crys-14',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '171',
    class: 'Crystals',
    valueName: '25MHz 20pF 30ppm',
    toleranceType: '6.0x3.5x1.1',
    footprint: 'ECS-250-18-23A-JGN-TR',
    manufacturer: 'NIC',
    mpn: '',
    vendor: '',
    sample: '',
    stock: '',
    moq: '',
    unitPriceTwd: '8.45',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-03-29',
    location: 'A棟-晶振架-14',
    safetyStock: 100
  },
  {
    id: 'p-crys-15',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '256',
    class: 'Crystals',
    valueName: '25MHz 6pF 10ppm',
    toleranceType: '5.0x3.2x1.4',
    footprint: '2.4x1.6x3.8 2pin',
    manufacturer: '加高電子(HELE)',
    mpn: 'HSX530G',
    vendor: '',
    sample: '0',
    stock: '',
    moq: '',
    unitPriceTwd: '',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-01',
    location: 'A棟-晶振架-15',
    safetyStock: 50
  },
  {
    id: 'p-crys-16',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '171',
    class: 'Crystals',
    valueName: '25MHz 20pF 20ppm',
    toleranceType: '5032貼片 無源晶振 2pin',
    footprint: '5.0x3.2x1.2 2pin',
    manufacturer: '',
    mpn: '',
    vendor: '',
    sample: '248',
    stock: '856+61',
    moq: '',
    unitPriceTwd: '2.1',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-05',
    location: 'A棟-晶振架-16',
    safetyStock: 500
  },
  {
    id: 'p-crys-17',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '246',
    class: 'Crystals',
    valueName: '24MHz 8PF 10PPM',
    toleranceType: '2016貼片 無源晶振',
    footprint: '2016',
    manufacturer: '',
    mpn: 'YSX211SL 24MHz',
    vendor: 'Sam',
    sample: '34',
    stock: '',
    moq: '',
    unitPriceTwd: '2.18',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-08',
    location: 'A棟-晶振架-17',
    safetyStock: 50
  },
  {
    id: 'p-crys-18',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '326',
    class: 'Crystals',
    valueName: '32MHz ±20ppm 12pF',
    toleranceType: '3225 貼片 無源晶振 4pin',
    footprint: '3.2x2.5x1',
    manufacturer: '',
    mpn: 'YSX321SL-32MHz',
    vendor: '',
    sample: '48',
    stock: '',
    moq: '',
    unitPriceTwd: '0.9',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-10',
    location: 'A棟-晶振架-18',
    safetyStock: 50
  },
  {
    id: 'p-crys-19',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '306',
    class: 'Crystals',
    valueName: '30MHz 10ppm 12pF',
    toleranceType: '3225 貼片 無源晶振 4pin',
    footprint: '3.2x2.5x1',
    manufacturer: 'YSX321SL',
    mpn: 'X322530MOB4SI',
    vendor: '',
    sample: '10',
    stock: '',
    moq: '',
    unitPriceTwd: '1.11',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-12',
    location: 'A棟-晶振架-19',
    safetyStock: 50
  },
  {
    id: 'p-crys-20',
    categoryId: 'cat-14',
    categoryPath: '零件 / 14(震盪器)',
    group: '14',
    type: '1',
    item: '306',
    class: 'Crystals',
    valueName: '30MHz 10ppm 20pF',
    toleranceType: '3225 貼片 無源晶振 4pin',
    footprint: '3.2x2.5x1',
    manufacturer: '',
    mpn: '',
    vendor: '',
    sample: '50',
    stock: '',
    moq: '',
    unitPriceTwd: '0.8',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-15',
    location: 'A棟-晶振架-20',
    safetyStock: 50
  },

  // --- 11X(電阻) 示範資料 ---
  {
    id: 'p-res-1',
    categoryId: 'cat-11x',
    categoryPath: '零件 / 11X(電阻)',
    group: '11',
    type: '1',
    item: '103',
    class: 'Resistors',
    valueName: '10kΩ ±1% 1/16W',
    toleranceType: '±1% 100ppm',
    footprint: '0402',
    manufacturer: 'Yageo 國巨',
    mpn: 'RC0402FR-0710KL',
    vendor: 'Mouser',
    sample: '200',
    stock: '15,000',
    moq: '10000',
    unitPriceTwd: '0.045',
    unitPriceUsd: '0.0015',
    substitute: '厚聲 / 華新科',
    date: '2026-04-10',
    location: 'A棟-電阻架-01',
    safetyStock: 5000
  },
  {
    id: 'p-res-2',
    categoryId: 'cat-11x',
    categoryPath: '零件 / 11X(電阻)',
    group: '11',
    type: '1',
    item: '472',
    class: 'Resistors',
    valueName: '4.7kΩ ±1% 1/10W',
    toleranceType: '±1%',
    footprint: '0603',
    manufacturer: 'Walsin 華新科',
    mpn: 'WR06X4701FTL',
    vendor: 'Arrow',
    sample: '50',
    stock: '800', // 低庫存展示
    moq: '5000',
    unitPriceTwd: '0.052',
    unitPriceUsd: '',
    substitute: '',
    date: '2026-04-12',
    location: 'A棟-電阻架-02',
    safetyStock: 2000
  },

  // --- 12X(電感) 示範資料 ---
  {
    id: 'p-ind-1',
    categoryId: 'cat-12x',
    categoryPath: '零件 / 12X(電感)',
    group: '12',
    type: '1',
    item: '100',
    class: 'Inductors',
    valueName: '10μH ±20% 3.2A',
    toleranceType: '屏蔽功率電感',
    footprint: '7x7x4mm',
    manufacturer: 'Coilcraft',
    mpn: 'MSS7341-103ML',
    vendor: 'Avnet',
    sample: '10+20',
    stock: '180', // 低庫存展示
    moq: '1000',
    unitPriceTwd: '12.5',
    unitPriceUsd: '0.42',
    substitute: '',
    date: '2026-04-14',
    location: 'A棟-電感架-01',
    safetyStock: 300
  },

  // --- 產品 -> RTK 示範資料 ---
  {
    id: 'p-rtk-1',
    categoryId: 'cat-rtk-base',
    categoryPath: '產品 / RTK / 基準站設備',
    group: '50',
    type: '1',
    item: 'RTK-01',
    class: 'RTK Product',
    valueName: '雙頻多星座 RTK 基準站主機',
    toleranceType: 'IP67 / 4G+UHF',
    footprint: '鋁合金外殼 220x180mm',
    manufacturer: '自行研發生產',
    mpn: 'PRD-RTK-BASE-V2',
    vendor: '內部產線',
    sample: '2',
    stock: '12',
    moq: '1',
    unitPriceTwd: '45,000',
    unitPriceUsd: '1,500',
    substitute: '',
    date: '2026-04-15',
    location: 'B棟-產品庫-RTK01',
    safetyStock: 5
  },
  {
    id: 'p-rtk-2',
    categoryId: 'cat-rtk-rover',
    categoryPath: '產品 / RTK / 手持移動站',
    group: '50',
    type: '2',
    item: 'RTK-02',
    class: 'RTK Product',
    valueName: '手持三防 RTK 移動測量終端',
    toleranceType: '5.5吋陽光螢幕 / 藍牙',
    footprint: '手持機',
    manufacturer: '自行研發生產',
    mpn: 'PRD-RTK-ROVER-M1',
    vendor: '內部產線',
    sample: '1',
    stock: '3', // 低庫存展示
    moq: '1',
    unitPriceTwd: '38,000',
    unitPriceUsd: '1,250',
    substitute: '',
    date: '2026-04-15',
    location: 'B棟-產品庫-RTK02',
    safetyStock: 10
  }
];

// 計算字串算式總數量 (如 "1+100+10" -> 111, "3,000" -> 3000, "856+61" -> 917)
function parseStockFormula(str) {
  if (!str) return 0;
  if (typeof str === 'number') return str;
  const clean = String(str).replace(/,/g, '').trim();
  if (!clean) return 0;
  
  // 安全評估加法算式
  if (/^[\d\s+.-]+$/.test(clean)) {
    try {
      const parts = clean.split('+').map(p => parseFloat(p.trim()) || 0);
      return parts.reduce((a, b) => a + b, 0);
    } catch (e) {
      return parseFloat(clean) || 0;
    }
  }
  return parseFloat(clean) || 0;
}

// 產生隨機重整展示數據
function generateRandomizedParts(baseList = INITIAL_PARTS_SEED) {
  return baseList.map(item => {
    // 複製並微調數量
    const copy = { ...item };
    if (copy.stock && copy.stock !== '') {
      const baseNum = parseStockFormula(copy.stock);
      const jitter = Math.floor((Math.random() - 0.5) * 0.3 * baseNum);
      const newStock = Math.max(0, baseNum + jitter);
      copy.stock = newStock.toLocaleString();
    }
    return copy;
  });
}
